#!/bin/bash
# Skript zum einfachen ein/ausschalten des Autostarts in der start.conf
# jesko.anschuetz@linuxmuster.net April 2013
#
# 
# usage: autostart GRUPPE LABEL [on/off]
#
# Der betroffene Autostart braucht ein Hilfslabel am Ende der Zeile:
# Bsp:
# Autostart = no # ubuntu12
# Wird ON/OFF weggelassen, schaltet das Skript den Status einfach um.

LINBOPFAD=/var/linbo
# Parameter in Variablen speichern, dabei den Linbo-Pfad automatisch ergänzen.
STARTCONF=$LINBOPFAD/start.conf.$1
LABEL=$2

# offensichtliche Bedienfehler abfangen

# Startkonfiguration existiert nicht:
if [ ! -e $STARTCONF ]
then
	echo $STARTCONF existiert nicht... Abbruch >&2
	exit 1
fi

# Label nicht vorhanden oder mehrdeutig
UNIQUE=$(grep "$LABEL" "$STARTCONF" | grep -c "utostart")
if [[ $UNIQUE != 1 ]]
then
	echo Label nicht vorhanden, nicht eindeutig oder nicht in einer Autostart-Zeile... >&2
	echo 'USAGE: autostart <start.conf.hwk> <label> <yes|no>'
	exit 1
fi

case "$3" in
	[oO][nN])
		SWITCH=ON
            	;;

	[oO][fF][fF])
		SWITCH=OFF
            	;;

  	*) 
		STATUSQUO=$(grep ubuntu /var/linbo/start.conf.lenny |grep utostart | cut -d" " -f3)
#		echo $STATUSQUO
		[[ "$STATUSQUO" == "yes" ]] && SWITCH=OFF || SWITCH=ON
     		;;
esac



# Zeile aus start.conf extrahieren
OLDLINE=$(grep "$LABEL" "$STARTCONF")

case "$SWITCH" in
	OFF)
		echo Autostart ausschalten...
		NEWLINE=$(echo $OLDLINE | sed -e 's/[yY][eE][sS]/no/g')
            	;;

	ON)
		echo Autostart anschalten...
		NEWLINE=$(echo $OLDLINE | sed -e 's/[nN][oO]/yes/g')
            	;;

  	*) 
		echo Irgendwas ist schief gelaufen, diese Zeile hätte nie ausgeführt werden dürfen...
		exit 1
     		;;
esac

sed -e "s/$OLDLINE/$NEWLINE/g" -i $STARTCONF

echo ...fertig

